// 离线翻译词典 v1.0
// 内置常用短语 + 句式匹配
var OFFLINE_DICT = {
// === 中文 → English 常用短语 ===
"你好":"Hello","你好吗":"How are you","谢谢":"Thank you","对不起":"Sorry","没关系":"It's OK",
"是的":"Yes","不是":"No","请":"Please","再见":"Goodbye","早上好":"Good morning",
"晚上好":"Good evening","晚安":"Good night","早上好啊":"Good morning","吃了吗":"Have you eaten",
"我很高兴":"I'm happy","我不明白":"I don't understand","你说什么":"What did you say",
"能再说一遍吗":"Can you say that again","我听不懂":"I can't understand","请问":"Excuse me",
"多少钱":"How much","在哪里":"Where is","什么时候":"When","为什么":"Why","怎么样":"How",
"好的":"OK","当然":"Of course","没问题":"No problem","等一下":"Wait a moment","马上":"Right away",
"我来了":"I'm here","我走了":"I'm leaving","吃饭":"Have a meal","喝水":"Drink water",
"工作":"Work","学习":"Study","休息":"Rest","睡觉":"Sleep","回家":"Go home",
"出门":"Go out","下雨了":"It's raining","天气":"Weather","热":"Hot","冷":"Cold",
"今天":"Today","明天":"Tomorrow","昨天":"Yesterday","现在":"Now","以后":"Later",
"喜欢":"Like","不喜欢":"Don't like","想要":"Want","需要":"Need","可以":"Can",
"不行":"Cannot","应该":"Should","必须":"Must","可能":"Maybe","一定":"Definitely",
"很好":"Very good","太好了":"Great","不错":"Not bad","加油":"Come on","厉害":"Amazing",
"真的吗":"Really","当然了":"Of course","我知道了":"I see","明白了":"Understood",
"谢谢你":"Thank you very much","不客气":"You're welcome","打扰了":"Sorry to bother you",
"祝你好运":"Good luck","生日快乐":"Happy birthday","新年快乐":"Happy new year",
"恭喜发财":"Congratulations","节日快乐":"Happy holiday","身体健康":"Stay healthy",
"万事如意":"All the best","心想事成":"May your wishes come true",
"我爱你":"I love you","我想你":"I miss you","你是我的":"You are mine",
"在一起":"Be together","分手":"Break up","结婚":"Get married",
"朋友":"Friend","家人":"Family","爸爸":"Dad","妈妈":"Mom","哥哥":"Brother",
"姐姐":"Sister","弟弟":"Brother","妹妹":"Sister","爷爷":"Grandpa","奶奶":"Grandma",
"儿子":"Son","女儿":"Daughter","老公":"Husband","老婆":"Wife","孩子":"Child",
"学校":"School","医院":"Hospital","银行":"Bank","超市":"Supermarket","餐厅":"Restaurant",
"酒店":"Hotel","机场":"Airport","车站":"Station","公园":"Park","电影院":"Cinema",
"图书馆":"Library","公司":"Company","办公室":"Office","家":"Home","房间":"Room",
"手机":"Phone","电脑":"Computer","电视":"TV","网络":"Internet","WiFi":"WiFi",
"苹果":"Apple","香蕉":"Banana","橘子":"Orange","葡萄":"Grape","西瓜":"Watermelon",
"米饭":"Rice","面条":"Noodles","面包":"Bread","牛奶":"Milk","咖啡":"Coffee",
"茶":"Tea","啤酒":"Beer","红酒":"Red wine","水":"Water","果汁":"Juice",
"鸡":"Chicken","鱼":"Fish","牛肉":"Beef","猪肉":"Pork","羊肉":"Lamb",
"蔬菜":"Vegetables","水果":"Fruit","鸡蛋":"Egg","豆腐":"Tofu","饺子":"Dumplings",
"中国":"China","美国":"America","日本":"Japan","韩国":"Korea","英国":"England",
"法国":"France","德国":"Germany","俄罗斯":"Russia","加拿大":"Canada","澳大利亚":"Australia",
"开":"Open","关":"Close","上":"Up","下":"Down","左":"Left","右":"Right",
"大":"Big","小":"Small","多":"Many","少":"Few","快":"Fast","慢":"Slow",
"新":"New","旧":"Old","好":"Good","坏":"Bad","贵":"Expensive","便宜":"Cheap",
"远":"Far","近":"Near","高":"Tall","矮":"Short","长":"Long","短":"Short",
"深":"Deep","浅":"Shallow","重":"Heavy","轻":"Light","硬":"Hard","软":"Soft",
"热":"Hot","冷":"Cold","温":"Warm","凉":"Cool","干":"Dry","湿":"Wet",
"亮":"Bright","暗":"Dark","吵":"Noisy","安静":"Quiet","美":"Beautiful","丑":"Ugly",
"富":"Rich","穷":"Poor","忙":"Busy","闲":"Free","累":"Tired","困":"Sleepy",
"饿":"Hungry","渴":"Thirsty","痛":"Pain","痒":"Itch","晕":"Dizzy","吐":"Vomit",
"感冒":"Cold","发烧":"Fever","咳嗽":"Cough","头疼":"Headache","肚子疼":"Stomachache",
"看医生":"See a doctor","吃药":"Take medicine","打针":"Get injection","挂号":"Register",
"药":"Medicine","医生":"Doctor","护士":"Nurse","病人":"Patient","健康":"Health",
"跑步":"Run","走路":"Walk","游泳":"Swim","骑车":"Ride a bike","开车":"Drive",
"坐车":"Take a car","坐飞机":"Take a plane","坐火车":"Take a train","坐地铁":"Take subway",
"上班":"Go to work","下班":"Get off work","加班":"Work overtime","请假":"Take leave",
"开会":"Meeting","打电话":"Make a call","发短信":"Send text","发邮件":"Send email",
"上网":"Go online","拍照":"Take photo","录视频":"Record video","玩游戏":"Play games",
"看电影":"Watch movie","听音乐":"Listen to music","唱歌":"Sing","跳舞":"Dance",
"画画":"Draw","写字":"Write","读书":"Read","做饭":"Cook","洗衣服":"Do laundry",
"打扫":"Clean","整理":"Organize","装修":"Renovate","搬家":"Move house",
"旅游":"Travel","度假":"Vacation","出差":"Business trip","签证":"Visa","护照":"Passport",
"行李":"Luggage","地图":"Map","导游":"Tour guide","景点":"Attraction","门票":"Ticket",
"排队":"Queue","拥挤":"Crowded","堵车":"Traffic jam","红绿灯":"Traffic light",
"拐弯":"Turn","直走":"Go straight","过马路":"Cross the road","人行道":"Sidewalk",
"自行车":"Bicycle","公交车":"Bus","出租车":"Taxi","地铁":"Subway","火车":"Train",
"飞机":"Airplane","船":"Ship","摩托车":"Motorcycle","停车":"Parking",
"春天":"Spring","夏天":"Summer","秋天":"Autumn","冬天":"Winter",
"星期一":"Monday","星期二":"Tuesday","星期三":"Wednesday","星期四":"Thursday",
"星期五":"Friday","星期六":"Saturday","星期天":"Sunday",
"一月":"January","二月":"February","三月":"March","四月":"April",
"五月":"May","六月":"June","七月":"July","八月":"August",
"九月":"September","十月":"October","十一月":"November","十二月":"December",
"小时":"Hour","分钟":"Minute","秒钟":"Second","今天星期几":"What day is it today",
"几点了":"What time is it","时间":"Time","日历":"Calendar","闹钟":"Alarm",
"生日":"Birthday","年龄":"Age","名字":"Name","性别":"Gender","男":"Male","女":"Female",
"地址":"Address","电话":"Phone number","邮箱":"Email","密码":"Password",
"微信":"WeChat","支付宝":"Alipay","淘宝":"Taobao","京东":"JD","拼多多":"Pinduoduo",
"抖音":"TikTok","快手":"Kuaishou","微博":"Weibo","小红书":"Xiaohongshu",
"百度":"Baidu","谷歌":"Google","苹果":"Apple","华为":"Huawei","小米":"Xiaomi",
"三星":"Samsung","特斯拉":"Tesla","亚马逊":"Amazon","微软":"Microsoft",
"成功":"Success","失败":"Failure","努力":"Effort","坚持":"Persist","放弃":"Give up",
"希望":"Hope","失望":"Disappointed","梦想":"Dream","目标":"Goal","计划":"Plan",
"机会":"Chance","风险":"Risk","挑战":"Challenge","困难":"Difficulty","解决":"Solve",
"经验":"Experience","教训":"Lesson","进步":"Progress","改变":"Change","发展":"Develop",
"创新":"Innovate","学习":"Learn","教":"Teach","练习":"Practice","考试":"Exam",
"毕业":"Graduate","工作":"Job","工资":"Salary","升职":"Promotion","辞职":"Resign",
"面试":"Interview","简历":"Resume","合同":"Contract","老板":"Boss","同事":"Colleague",
"客户":"Customer","产品":"Product","服务":"Service","价格":"Price","质量":"Quality",
"市场":"Market","竞争":"Competition","利润":"Profit","投资":"Invest","贷款":"Loan",
"税":"Tax","保险":"Insurance","基金":"Fund","股票":"Stock","理财":"Finance",
"文化":"Culture","历史":"History","艺术":"Art","音乐":"Music","电影":"Movie",
"书":"Book","新闻":"News","科技":"Technology","科学":"Science","数学":"Math",
"物理":"Physics","化学":"Chemistry","生物":"Biology","地理":"Geography",
"政治":"Politics","经济":"Economy","社会":"Society","环境":"Environment",
"动物":"Animal","植物":"Plant","花":"Flower","树":"Tree","草":"Grass",
"山":"Mountain","河":"River","湖":"Lake","海":"Sea","沙漠":"Desert",
"森林":"Forest","天空":"Sky","云":"Cloud","雨":"Rain","雪":"Snow",
"风":"Wind","雷":"Thunder","闪电":"Lightning","彩虹":"Rainbow","星星":"Star",
"月亮":"Moon","太阳":"Sun","地球":"Earth","宇宙":"Universe","太空":"Space",

// === English → 中文 ===
"hello":"你好","hi":"你好","hey":"嗨","goodbye":"再见","bye":"再见",
"thank you":"谢谢","thanks":"谢谢","sorry":"对不起","please":"请",
"yes":"是的","no":"不是","ok":"好的","okay":"好的","sure":"当然",
"good":"好","bad":"坏","great":"很好","nice":"不错","wonderful":"太好了",
"amazing":"厉害","awesome":"太棒了","perfect":"完美","beautiful":"美丽",
"ugly":"丑陋","happy":"开心","sad":"伤心","angry":"生气","afraid":"害怕",
"love":"爱","like":"喜欢","hate":"恨","want":"想要","need":"需要",
"can":"可以","cannot":"不行","must":"必须","should":"应该","might":"可能",
"i love you":"我爱你","i miss you":"我想你","good morning":"早上好",
"good evening":"晚上好","good night":"晚安","see you":"再见",
"how are you":"你好吗","i'm fine":"我很好","i'm happy":"我很高兴",
"i'm sorry":"对不起","excuse me":"请问","thank you very much":"非常感谢",
"you're welcome":"不客气","have a good day":"祝你有美好的一天",
"happy birthday":"生日快乐","merry christmas":"圣诞快乐",
"happy new year":"新年快乐","congratulations":"恭喜","cheers":"干杯",
"i don't understand":"我不明白","can you help me":"你能帮我吗",
"where is":"在哪里","how much":"多少钱","what time":"几点",
"i want":"我想要","i need":"我需要","i can":"我可以","let's go":"我们走",
"come here":"过来","go away":"走开","sit down":"坐下","stand up":"站起来",
"open":"打开","close":"关闭","start":"开始","stop":"停止","wait":"等等",
"eat":"吃","drink":"喝","sleep":"睡觉","work":"工作","play":"玩",
"read":"读","write":"写","listen":"听","speak":"说","look":"看",
"walk":"走","run":"跑","swim":"游泳","fly":"飞","drive":"开车",
"home":"家","school":"学校","hospital":"医院","bank":"银行","hotel":"酒店",
"airport":"机场","restaurant":"餐厅","shop":"商店","park":"公园","office":"办公室",
"father":"爸爸","mother":"妈妈","brother":"兄弟","sister":"姐妹","son":"儿子",
"daughter":"女儿","husband":"丈夫","wife":"妻子","friend":"朋友","family":"家人",
"water":"水","food":"食物","money":"钱","time":"时间","day":"天","night":"夜晚",
"morning":"早上","afternoon":"下午","evening":"晚上","today":"今天",
"tomorrow":"明天","yesterday":"昨天","now":"现在","later":"以后","always":"总是",
"never":"从不","sometimes":"有时候","often":"经常","usually":"通常",
"big":"大","small":"小","long":"长","short":"短","tall":"高","old":"旧",
"new":"新","hot":"热","cold":"冷","fast":"快","slow":"慢","easy":"容易",
"hard":"难","right":"对","wrong":"错","same":"相同","different":"不同",
"i am":"我是","you are":"你是","he is":"他是","she is":"她是","it is":"它是",
"we are":"我们是","they are":"他们是","this is":"这是","that is":"那是",
"what":"什么","who":"谁","where":"哪里","when":"什么时候","why":"为什么",
"how":"怎么","which":"哪个","because":"因为","so":"所以","but":"但是",
"and":"和","or":"或者","if":"如果","then":"那么","very":"非常",
"really":"真的","just":"只是","also":"也","too":"也","already":"已经",
"still":"还是","again":"再","more":"更多","most":"最多","less":"更少",
"here":"这里","there":"那里","everywhere":"到处","nowhere":" nowhere",
"everyone":"每个人","someone":"某人","nobody":"没有人","something":"某事",
"nothing":"没有什么","everything":"一切","always":"总是","never":"从不",
"sometimes":"有时","often":"经常","usually":"通常","rarely":"很少",
"monday":"星期一","tuesday":"星期二","wednesday":"星期三","thursday":"星期四",
"friday":"星期五","saturday":"星期六","sunday":"星期天",
"january":"一月","february":"二月","march":"三月","april":"四月",
"may":"五月","june":"六月","july":"七月","august":"八月",
"september":"九月","october":"十月","november":"十一月","december":"十二月",
"one":"一","two":"二","three":"三","four":"四","five":"五","six":"六",
"seven":"七","eight":"八","nine":"九","ten":"十","hundred":"百","thousand":"千",
"million":"百万","billion":"十亿","zero":"零",
"red":"红色","blue":"蓝色","green":"绿色","yellow":"黄色","black":"黑色",
"white":"白色","pink":"粉色","purple":"紫色","orange":"橙色","brown":"棕色",
"gray":"灰色","grey":"灰色","gold":"金色","silver":"银色",
"china":"中国","chinese":"中文","english":"英语","japanese":"日语","korean":"韩语",
"french":"法语","german":"德语","spanish":"西班牙语","russian":"俄语",
"american":"美国人","british":"英国人","japanese":"日本人","korean":"韩国人",
"iphone":"iPhone","android":"安卓","computer":"电脑","internet":"互联网",
"software":"软件","hardware":"硬件","website":"网站","app":"应用","data":"数据",
"password":"密码","email":"邮件","photo":"照片","video":"视频","music":"音乐",
"movie":"电影","book":"书","game":"游戏","sport":"运动","food":"食物",
"weather":"天气","rain":"雨","snow":"雪","sun":"太阳","moon":"月亮",
"star":"星星","sky":"天空","cloud":"云","wind":"风","ocean":"海洋",
"mountain":"山","river":"河","lake":"湖","forest":"森林","tree":"树",
"flower":"花","animal":"动物","dog":"狗","cat":"猫","bird":"鸟","fish":"鱼",
"horse":"马","cow":"牛","pig":"猪","chicken":"鸡","sheep":"羊",
"apple":"苹果","banana":"香蕉","orange":"橙子","grape":"葡萄","watermelon":"西瓜",
"rice":"米饭","noodle":"面条","bread":"面包","milk":"牛奶","coffee":"咖啡",
"tea":"茶","beer":"啤酒","wine":"酒","juice":"果汁","water":"水",
"chicken":"鸡肉","beef":"牛肉","pork":"猪肉","fish":"鱼肉","egg":"鸡蛋",
"car":"汽车","bus":"公交车","train":"火车","plane":"飞机","ship":"船",
"bike":"自行车","taxi":"出租车","subway":"地铁","road":"路","street":"街道",
"hospital":"医院","school":"学校","church":"教堂","museum":"博物馆","library":"图书馆",
"doctor":"医生","nurse":"护士","teacher":"老师","student":"学生","engineer":"工程师",
"boss":"老板","worker":"工人","driver":"司机","police":"警察","lawyer":"律师",
"sunny":"晴天","cloudy":"多云","rainy":"下雨","snowy":"下雪","windy":"有风",
"hot":"热","cold":"冷","warm":"温暖","cool":"凉爽","humid":"潮湿",
};

// 离线翻译函数
function offlineTranslate(text, fromLang, toLang) {
  var dict = OFFLINE_DICT;
  var lower = text.toLowerCase().trim();
  
  // 精确匹配
  if (dict[lower]) return dict[lower];
  
  // 尝试逐词翻译
  var words = lower.split(/[\s,，。！？!?.]+/);
  var translated = [];
  var foundAny = false;
  
  for (var i = 0; i < words.length; i++) {
    var w = words[i];
    if (dict[w]) {
      translated.push(dict[w]);
      foundAny = true;
    } else {
      translated.push(w); // 保留原文
    }
  }
  
  if (foundAny && translated.join(' ') !== lower) {
    return translated.join(' ');
  }
  
  return ''; // 无法翻译
}
